export const blogPosts = [
    {
      id: 'projektstart',
      title: 'The Nightmare Lake',
      date: '10.09.25',
      url: '/blog/projektstart',
      content: 'There is a lake in distant Zan, Beyond the wonted haunts of man, Where broods alone in a hideous state A spirit dead and desolate; A spirit ancient and unholy, Heavy with fearsome melancholy, Which from the waters dull and dense Draws vapors cursed with pestilence. Around the banks, a mire of clay, Sprawl things offensive in decay, And curious birds that reach that shore Are seen by mortals nevermore. Here shines by day the searing sun On glassy wastes beheld by none, And here by night pale moonbeams flow Into the deeps that yawn below. In nightmares only is it told What scenes beneath those beams unfold; What scenes, too old for human sight, Lie sunken there in endless night; For in those depths there only pace The shadows of a voiceless race. One midnight, redolent of ill, I saw that lake, asleep and still; While in the lurid sky there rode A gibbous moon that glow’d and glow’d. I saw the stretching marshy shore, And the foul things those marshes bore: Lizards and snakes convuls’d and dying; Ravens and vampires putrefying; All these, and hov’ring o’er the dead, Narcophagi that on them fed. And as the dreadful moon climb’d high, Fright’ning the stars from out the sky, I saw the lake’s dull water glow Till sunken things appear’d below. There shone unnumber’d fathoms down, The tow’rs of a forgotten town; The tarnish’d domes and mossy walls; Weed-tangled spires and empty halls; Deserted fanes and vaults of dread, And streets of gold uncoveted. These I beheld, and saw beside A horde of shapeless shadows glide; A noxious horde which to my glance Seem’d moving in a hideous dance Round slimy sepulchres that lay Beside a never-travell’d way. Straight from those tombs a heaving rose That vex’d the waters’ dull repose, While lethal shades of upper space Howl’d at the moon’s sardonic face. Then sank the lake within its bed, Suck’d down to caverns of the dead, Till from the reeking, new-stript earth Curl’d foetid fumes of noisome birth. About the city, nigh uncover’d, The monstrous dancing shadows hover’d, When lo! there oped with sudden stir The portal of each sepulchre! No ear may learn, no tongue may tell What nameless horror then befell. I see that lake—that moon agrin—That city and the things within—Waking, I pray that on that shore The nightmare lake may sink no more!'
    },
    {
        id: 'test1',
        title: 'Wie lang ist zu lang?',
        date: '',
        url: '/blog/test1',
        content: 'When age fell upon the world, and wonder went out of the minds of men; when grey cities reared to smoky skies tall towers grim and ugly, in whose shadow none might dream of the sun or of spring’s flowering meads; when learning stripped earth of her mantle of beauty, and poets sang no more save of twisted phantoms seen with bleared and inward-looking eyes; when these things had come to pass, and childish hopes had gone away forever, there was a man who travelled out of life on a quest into the spaces whither the world’s dreams had fled. Of the name and abode of this man but little is written, for they were of the waking world only; yet it is said that both were obscure. It is enough to know that he dwelt in a city of high walls where sterile twilight reigned, and that he toiled all day among shadow and turmoil, coming home at evening to a room whose one window opened not on the fields and groves but on a dim court where other windows stared in dull despair. From that casement one might see only walls and windows, except sometimes when one leaned far out and peered aloft at the small stars that passed. And because mere walls and windows must soon drive to madness a man who dreams and reads much, the dweller in that room used night after night to lean out and peer aloft to glimpse some fragment of things beyond the waking world and the greyness of tall cities. After years he began to call the slow-sailing stars by name, and to follow them in fancy when they glided regretfully out of sight; till at length his vision opened to many secret vistas whose existence no common eye suspects. And one night a mighty gulf was bridged, and the dream-haunted skies swelled down to the lonely watcher’s window to merge with the close air of his room and make him a part of their fabulous wonder. There came to that room wild streams of violet midnight glittering with dust of gold; vortices of dust and fire, swirling out of the ultimate spaces and heavy with perfumes from beyond the worlds. Opiate oceans poured there, litten by suns that the eye may never behold and having in their whirlpools strange dolphins and sea-nymphs of unrememberable deeps. Noiseless infinity eddied around the dreamer and wafted him away without even touching the body that leaned stiffly from the lonely window; and for days not counted in men’s calendars the tides of far spheres bare him gently to join the dreams for which he longed; the dreams that men have lost. And in the course of many cycles they tenderly left him sleeping on a green sunrise shore; a green shore fragrant with lotus-blossoms and starred by red camalotes.'
    } 
    
];